### ISSUE TITLE
Prepare meta information

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#1]
We need to complete the following meta properties:

- [x] Title
- [x] Description
- [x] Keywords (optional)
- [x] Share Image
- [x] Twitter username (optional)

**Comment by jangustia** [comment]
- Title: Juan Angustia - Visual Designer
- Description: A Visual Designer at Google, who loves to create simple designs that inspire and engage people, an aspiring writing, fashion lover, and also a proud Afro-Latino.
- Keywords: Visual Designer, Juan Angustia, Dominican, Angustia, UX, UI, Product Designer, Prototypes, Freelance
- Share image, Use the one that I have on the Hello Section
- Twitter: @memoplus

**Comment by jangustia** [comment]
![Angustia-share-image](https://user-images.githubusercontent.com/1208621/81533799-af241900-931b-11ea-8b42-dcdd973f4c1b.jpg)
Aquí esta la imagen.
