### ISSUE TITLE
Parallax video

### ISSUE THREAD

**Issue by jangustia** [antoniwan/jc-angustia-2020#10]
Here you can see the type of parallax that I want on the video and the video that we can use for the moment is the one that I have on my current portfolio.

Check contact section:
http://jcagarcia.com/

[Final video](https://vimeo.com/415724764)

**Comment by antoniwan** [comment]
@jangustia pregunta:

¿el video va 100% width o se mantiene con el max-width?

**Comment by antoniwan** [comment]
determinamos que va 100% tal y como está en http://jcagarcia.com/

**Comment by jangustia** [comment]
Aquí tienes un ejemplo de como visualizo el video parallax https://www.vevo.com/about abajo mira la foto de los chicps.
