### ISSUE TITLE
Animated

### ISSUE THREAD

**Issue by jangustia** [antoniwan/jc-angustia-2020#11]
Hey mira lo que encontré en Chrome Canary, esto puede ser algo interesante animar las particula así como hace Chrome Canary

https://drive.google.com/file/d/1H6nz4REFV-rTspPCrAtBrNgQGkED15pT/view?usp=sharing

**Comment by antoniwan** [comment]
Voy a check it out. De seguro están utilizando un <canvas /> element, gracias.
