### ISSUE TITLE
Form validation & submission

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#12]
- [x] validation
- [x] submit
- [ ] reply user with a thank you email (?) 
- [ ] send email to JC's email

**Comment by antoniwan** [comment]
@jangustia  estoy pensando que estaría chévere si cuando el usuario someta la forma se le envie un email de "gracias por contactarme", ¿haces un html email template sencillito (SUPER SENCILLO POR FA'! LOL)? ¿Que te parece esta idea?

Entonces, voy a guardar los mensajes que te envien en una base de datos en el cloud (Google Firebase) y tambien te voy a enviar la información via email -- este email NO necesita template, utilizaré uno genérico.

Es posible que tengamos que añadir un CAPTCHA a esta forma, we'll see.

**Comment by antoniwan** [comment]
Hey @jangustia necesitamos diseñar un Loading state y un "Gracias" state para cuando se envia la forma.

**Comment by antoniwan** [comment]
Acabo de terminar el validation y submission, y añadi errores y sent states.

@jangustia  hay que revisar el diseño y el copy de todos estos elementos y states.

**Comment by jangustia** [comment]
The template design is on Figma.
