### ISSUE TITLE
Discuss form styles

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#13]
@jangustia estaba en proceso de hacer el estilo de las formas tal y como lo tienes en el Figma file pero por error resultó lo que tengo ahora, donde la forma está opaca hasta que le haces focus al input field, entonces se pone azul.

A mi me parece mejor UX como está ahora, pero lo dejo a tu discreción. 

Hacer el cambio de hacerlo siempre azul no me tomará ni 2 minutos, pero quería saber tu opinión.

**Comment by jangustia** [comment]
No esta mal, pero prefiero azul es un tema más de branding y también para crear un mejor contraste en los campos. Y como focus states puede probar cambiandolo a negro o a un azul mas clarito.
