### ISSUE TITLE
Prepare favicon and web application icons

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#2]
We need a favicon and web application icons in the following sizes:

- [x] 64x64
- [x] 192x192
- [x] 512x512

**Comment by jangustia** [comment]
[favicon.zip](https://github.com/antoniwan/jc-angustia-2020/files/4584658/favicon.zip)

**Comment by jangustia** [comment]
Favicon done!

**Comment by antoniwan** [comment]
perfecto @jangustia, ya están arriba. closing this ticket.
