### ISSUE TITLE
First round of feedbacks 

### ISSUE THREAD

**Issue by jangustia** [antoniwan/jc-angustia-2020#22]
Here my first visual feedback for the website. Update the font for **Futura PT**. You gonna need to convert to web font. [Download](https://drive.google.com/drive/folders/1EzlS2QoAdWbsbaFxH10C7n6w7chFpZLd?usp=sharing)

- [x] 0. Spacing between columns.
- [x] 1. Body max-width. Make sure that all these elements are aligned
- [x] 2. Copy block max-width; Make sure that all this copy has the same width.
- [x] 3. Move this graphic to the right to align more with the computer.
- [x] 4. Images width.
- [x] 5. Add more padding between sections. This is will help with the parallax effect between sections
- [x] 6. Make video height a bit taller, take this as an example.
- [x] 7. Reduce this space to O. I want to alight send button with the “scroll up” FAB button “Circle”.
- [x] 8. Alight this button with the form send button.

![feedback-01](https://user-images.githubusercontent.com/1208621/81898111-df162b00-956c-11ea-8895-dc8798e8a2ed.png)

**Comment by antoniwan** [comment]
@jangustia  voy a crear un issue nuevo para el font update.

**Comment by jangustia** [comment]
Buen progreso brother, pero te deje unos detalles pequeños


![round-2](https://user-images.githubusercontent.com/1208621/82111410-eae32800-96f9-11ea-8b23-ee0f43564dda.png)
