### ISSUE TITLE
Prepare mobile styles for several components

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#3]
- [x] Header
- [ ] One of the big hero elements
- [x] Rotators
- [x] Footer

**Comment by jangustia** [comment]
I added the mobile style

**Comment by antoniwan** [comment]
Thanks, checking it out!

**Comment by jangustia** [comment]
![mobile-treatment](https://user-images.githubusercontent.com/1208621/81533998-1215b000-931c-11ea-992f-79930d07876d.png)

Make sure that Hello section looks like this mock. Also the other sections too.
