### ISSUE TITLE
Deliver social media links

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#4]
- [ ] Twitter
- [ ] Instagram
- [ ] Behance

**Comment by jangustia** [comment]
- [Instagram](https://www.instagram.com/jcagarcia/)
-[ Twitter](https://twitter.com/memoplus)
- [Behance ](https://www.behance.net/jcagarcia)

**Comment by jangustia** [comment]
I add to more icons: Medium and Vimeo. Check the order on Figma.
