### ISSUE TITLE
El video siento que hay que pulirlo

### ISSUE THREAD

**Issue by jangustia** [antoniwan/jc-angustia-2020#41]
Siento que el video aun tiene un bug. Mira encontré el parallax que quiero, toma el código.

[Demo](https://codepen.io/adetr/pen/gvYJPM)

**Comment by antoniwan** [comment]
Voy a utilizar esa libreria que me pasaste. Actualmente estoy haciendo algo que yo escribí pero jarallax es mucho mas smooth.
