### ISSUE TITLE
Fix mobile styles for the footer

### ISSUE THREAD

**Issue by antoniwan** [antoniwan/jc-angustia-2020#7]

**Comment by antoniwan** [comment]
Oye @jangustia ahora con todos los icons se pone un poco apretado esto.

![Screen Shot 2020-05-07 at 11 22 24 AM](https://user-images.githubusercontent.com/588388/81312832-152b4a80-9055-11ea-857f-1d26ecf747cf.jpg)

Por ahora lo tengo así:

![Screen Shot 2020-05-07 at 11 31 01 AM](https://user-images.githubusercontent.com/588388/81313757-48220e00-9056-11ea-8375-6d5b2314feb0.jpg)

**Comment by jangustia** [comment]
Tienes razón, me gusta sin el logo.  Mas limpio.

**Comment by antoniwan** [comment]
gracias.
