### ISSUE TITLE
Links on Hero copy

### ISSUE THREAD

**Issue by jangustia** [antoniwan/jc-angustia-2020#8]
Please add this hyperlink on the words.

- [**Google**](https://students.googleblog.com/2020/02/my-path-to-google-juan-angustia-visual.html)
- [ **aspiring writing**](https://medium.com/@angustia/a-latino-college-dropout-at-google-5eb2d0629710)
- [**fashion lover**](https://www.instagram.com/p/B7JBE0ogWne/)

**Comment by antoniwan** [comment]
Añadí los links en el Hello component. Ahora, me parece que el bold de "Afro-Latino" da la impresión de que también es 'clickable'.

**Comment by jangustia** [comment]
Ahi pienso agregar otro enlace, no estoy seguro aun cual articulo. Por el momento podemos quitarle el bold.
